-- Migration: 0022_d5_seed_categories
-- D-5 Full Import: Appliance Categories Seed (idempotent)
--
-- Generated by generate-d5-seed.ts · 2026-05-25T16:20:10.239Z
--
-- Prereq: 0012_repair_master_data (repair_appliance_categories must exist)
-- Rollback: DELETE FROM repair_appliance_categories WHERE code IN ('desktop_pc');
--           (other categories seeded in 0016 — leave as-is)

INSERT INTO "repair_appliance_categories" ("code", "label_th", "label_en", "sort_order", "is_active")
VALUES
  ('ac', 'แอร์', 'Air Conditioner', 1, TRUE),
  ('refrigerator', 'ตู้เย็น', 'Refrigerator', 2, TRUE),
  ('washer', 'เครื่องซักผ้า', 'Washing Machine', 3, TRUE),
  ('computer', 'คอมพิวเตอร์', 'Computer/PC', 4, TRUE),
  ('tv', 'โทรทัศน์', 'Television', 5, TRUE),
  ('smartphone', 'สมาร์ทโฟน/มือถือ', 'Smartphone', 6, TRUE),
  ('notebook', 'โน้ตบุ๊ก/แล็ปท็อป', 'Notebook/Laptop', 7, TRUE),
  ('monitor', 'มอนิเตอร์', 'Monitor', 8, TRUE),
  ('printer', 'เครื่องพิมพ์', 'Printer', 9, TRUE),
  ('tablet', 'แท็บเล็ต', 'Tablet', 10, TRUE),
  ('microwave', 'ไมโครเวฟ', 'Microwave Oven', 11, TRUE),
  ('fan', 'พัดลม', 'Electric Fan', 12, TRUE),
  ('desktop_pc', 'คอมพิวเตอร์ตั้งโต๊ะ', 'Desktop PC', 13, TRUE)
ON CONFLICT ("code") DO UPDATE SET
  "label_th"   = EXCLUDED."label_th",
  "label_en"   = EXCLUDED."label_en",
  "sort_order" = EXCLUDED."sort_order",
  "updated_at" = NOW();
